# Risk Management Configuration

# Margin and Liquidation Settings
margin_settings:
  minimum_margin_buffer: 0.15  # 15% minimum margin buffer
  warning_margin_buffer: 0.25  # 25% warning threshold
  critical_margin_buffer: 0.20  # 20% critical threshold
  max_leverage: 10.0  # Maximum allowed leverage

# Position Management
position_limits:
  max_position_size: 1000000  # Maximum position size in USD
  max_position_ratio: 0.1  # Maximum position size as ratio of portfolio
  position_concentration_limit: 0.3  # Maximum concentration in single asset

# Stop Loss Settings
stop_loss:
  initial_stop_loss: 0.02  # Initial stop loss as percentage
  trailing_stop_loss: 0.015  # Trailing stop loss as percentage
  max_daily_loss: 0.05  # Maximum daily loss as percentage
  max_drawdown: 0.15  # Maximum drawdown before trading halt

# Volatility Settings
volatility:
  lookback_period: 24  # hours
  volatility_scaling: true
  max_volatility: 0.5  # Maximum allowed volatility
  min_volatility: 0.05  # Minimum volatility for position sizing

# Value at Risk (VaR)
var_settings:
  confidence_level: 0.99
  time_horizon: 24  # hours
  historical_window: 30  # days
  max_var_ratio: 0.1  # Maximum VaR as ratio of portfolio

# Risk Monitoring
monitoring:
  update_interval: 60  # seconds
  alert_threshold: 0.8  # Alert at 80% of any limit
  log_level: INFO
  retry_attempts: 3
  retry_delay: 5  # seconds

# Portfolio Management
portfolio:
  rebalancing_threshold: 0.1  # 10% deviation triggers rebalancing
  min_trade_size: 100  # Minimum trade size in USD
  max_slippage: 0.003  # Maximum allowed slippage
  correlation_threshold: 0.7  # Maximum correlation between positions
