# Development Environment Settings
# Configure development parameters.

environment: development

# Trading Parameters
trading:
  max_position_size: 100000  # Maximum position size in USD
  max_leverage: 10
  default_leverage: 5
  min_trade_size: 100  # Minimum trade size in USD
  max_trades_per_hour: 100
  max_open_positions: 5

# Risk Management
risk:
  max_drawdown_percent: 20
  daily_loss_limit_percent: 5
  position_risk_limit_percent: 2
  kelly_fraction: 0.5
  stop_loss_percent: 2
  take_profit_percent: 4

# Data Collection
data:
  historical_data_path: "data/raw/hyperliquid_api"
  processed_data_path: "data/processed"
  backup_path: "data/backups"
  update_interval_seconds: 60
  max_historical_days: 365

# Model Training
training:
  batch_size: 64
  learning_rate: 0.0001
  epochs: 100
  validation_split: 0.2
  early_stopping_patience: 10
  checkpoint_path: "models/checkpoints"

# Monitoring
monitoring:
  log_level: "INFO"
  metrics_update_interval: 60
  dashboard_update_interval: 300
  alert_cooldown_minutes: 15

# API Settings
api:
  retry_attempts: 3
  timeout_seconds: 30
  rate_limit_per_minute: 120

# Feature Engineering
features:
  price_features:
    - "close"
    - "volume"
    - "open"
    - "high"
    - "low"
  technical_indicators:
    - "rsi"
    - "macd"
    - "bollinger_bands"
  market_features:
    - "funding_rate"
    - "open_interest"
    - "market_depth"